# Isaachic Simulation: Adaptive Metabolic Brain
# Base logic by Isaac MX Nielens (March 2026)
# Features: Labor-Time Vouchers, Dynamic ENLT, Metabolic Ticks, and Adaptive Redirects

import random

class ResourceBank:
    def __init__(self):
        # Earth's Registry: capacity vs current available stock
        self.registry = {
            "Bread": {"capacity": 1000, "current": 900, "regrow_rate": 0.05}, 
            "Medicine": {"capacity": 500, "current": 450, "regrow_rate": 0.0}, 
            "Water": {"capacity": 5000, "current": 4800, "regrow_rate": 0.10}, 
            "Steel": {"capacity": 1000, "current": 150, "regrow_rate": 0.0}, 
            "Wood": {"capacity": 1200, "current": 600, "regrow_rate": 0.08}, 
            "Electricity": {"capacity": 2000, "current": 1800, "regrow_rate": 0.20}, 
            "Plastic": {"capacity": 1500, "current": 400, "regrow_rate": 0.0}, 
            "Healthcare": {"capacity": 1000, "current": 1000, "regrow_rate": 0.0}
        }

    def tick(self):
        """The 'Earth' heals during this phase."""
        print("\n>>> METABOLIC TICK: The Earth is regenerating... <<<")
        for name, res in self.registry.items():
            if res["regrow_rate"] > 0:
                growth = res["capacity"] * res["regrow_rate"]
                res["current"] = min(res["capacity"], res["current"] + growth)
                print(f"  * {name} regenerated by {growth:.1f} units.")

    def get_enlt_multiplier(self, resource_name):
        if resource_name in self.registry:
            res = self.registry[resource_name]
            return res["capacity"] / max(res["current"], 1)
        return 1.0

    def deplete(self, resource_name, amount):
        if resource_name in self.registry:
            self.registry[resource_name]["current"] -= (amount * 0.1)
            if self.registry[resource_name]["current"] < 0:
                self.registry[resource_name]["current"] = 0

class CentralPlan:
    def __init__(self, resource_bank):
        self.bank = resource_bank
        # THE ADAPTIVE MAP: If Key is Vetoed, try these in order
        self.substitutes = {
            "Steel": ["Wood", "Plastic"],
            "Wood": ["Plastic", "Steel"],
            "Plastic": ["Wood", "Bread"], # Bread as organic 'plastic' alternative logic
        }
        
        self.products = {
            "Bread": {"planned_labor": 100, "spent_vouchers": 0, "base_enlt": 5},
            "Medicine": {"planned_labor": 50, "spent_vouchers": 0, "base_enlt": 20},
            "Water": {"planned_labor": 150, "spent_vouchers": 0, "base_enlt": 80},
            "Wood": {"planned_labor": 120, "spent_vouchers": 0, "base_enlt": 60},
            "Steel": {"planned_labor": 200, "spent_vouchers": 0, "base_enlt": 100},
            "Electricity": {"planned_labor": 160, "spent_vouchers": 0, "base_enlt": 70},
            "Plastic": {"planned_labor": 140, "spent_vouchers": 0, "base_enlt": 50},
            "Healthcare": {"planned_labor": 250, "spent_vouchers": 0, "base_enlt": 90},
        }
    def innovate(self):
        """Simulates technological progress reducing ecological impact."""
        target = random.choice(list(self.products.keys()))
        reduction = 0.15 # 15% efficiency gain
        self.products[target]["base_enlt"] *= (1 - reduction)
        print(f"\n[TECH BREAKTHROUGH] New production methods for {target} found! Ecological cost reduced by 15%.")
    def process_consumption(self, product_name, amount):
        if product_name in self.products:
            self.products[product_name]["spent_vouchers"] += amount
            self.bank.deplete(product_name, amount)

    def calculate_suv(self):
        print("\n" + "="*80)
        print("--- ISAACHIC-CYBERNETIC FEEDBACK (THE PID SIGNAL) ---")
        print(f"{'Product':12} | {'SUV':4} | {'PS':4} | {'Metabolic Action / Advisory'}")
        print("-" * 80)
        
        # Phase 1: Pre-calculate all Priority Scores (The Brain's View)
        ps_scores = {}
        for name, data in self.products.items():
            suv = data["spent_vouchers"] / data["planned_labor"]
            multiplier = self.bank.get_enlt_multiplier(name)
            ps_scores[name] = (data["planned_labor"] * suv) / (data["base_enlt"] * multiplier)

        # Phase 2: Adjudicate and suggest Redirects
        total_satisfaction = 0
        for name, ps in ps_scores.items():
            suv = self.products[name]["spent_vouchers"] / self.products[name]["planned_labor"]
            
            if ps < 1.0:
                action = "VETOED"
                satisfaction = 0.0  # Total frustration
                # Check for healthy substitutes
                if name in self.substitutes:
                    for alt in self.substitutes[name]:
                        # Only redirect if the alternative is healthy (PS > 1.5)
                        if alt in ps_scores and ps_scores[alt] > 1.5:
                            action = f"VETOED -> REDIRECT to {alt}"
                            satisfaction = 0.5  # Partial satisfaction from redirect
                            print(f"  * {name} is VETOED. Redirecting to {alt} with PS {ps_scores[alt]:.2f}.")
                            break
                total_satisfaction += satisfaction
            elif suv > 1.0:
                action = "INCREASE PRODUCTION"
                total_satisfaction += 1.0  # Total fulfillment
            elif suv < 1.0:
                action = "DECREASE PRODUCTION"
                total_satisfaction += 1.0  # Total fulfillment
            else:
                action = "STASIS (Equilibrium)"
                total_satisfaction += 1.0  # Total fulfillment
            
            print(f"{name:12} | {suv:.2f} | {ps:.2f} | {action}")
            
        # Final Indices
        self.social_stability = (total_satisfaction / len(self.products)) * 100
        print("-" * 80)
        print(f"SOCIAL STABILITY INDEX: {self.social_stability:.1f}%")
        if self.social_stability < 70:
            print("WARNING: Low Social Stability! Consider Tech-Investment to lower ENLT.")
            

class IsaachicAgent:
    def __init__(self, name, training_hours, career_expected_hours):
        self.name = name
        self.v_hour = 1 + (training_hours / career_expected_hours)
        self.vouchers = 0

    def work(self, actual_hours):
        credit = actual_hours * self.v_hour
        self.vouchers += credit
        return credit

# --- EXECUTION: THE 10-YEAR CIVILIZATION LOOP ---#
earth = ResourceBank()
plan = CentralPlan(earth)

surgeon = IsaachicAgent("Specialist", 20000, 40000)
laborer = IsaachicAgent("Baseline", 0, 40000)

for year in range(1, 11):
    print(f"\n" + "#"*40)
    print(f"       STARTING YEAR {year}")
    print("#"*40)
    
    # 1. LABOR
    surgeon.work(40); laborer.work(40)

    # 2. CONSUMPTION (Now including the "Life Essentials")
    base_demand = 100 + (year * 5) 
    plan.process_consumption("Bread", base_demand * 1.2)
    plan.process_consumption("Water", base_demand * 2.0)       # Vital: High Demand
    plan.process_consumption("Medicine", base_demand * 0.5)    # Vital: Steady Demand
    plan.process_consumption("Electricity", base_demand * 1.5) # Vital: Growing Demand
    plan.process_consumption("Healthcare", base_demand * 1.0)
    plan.process_consumption("Wood", base_demand * 0.8)
    plan.process_consumption("Steel", base_demand * 0.4) 
    plan.process_consumption("Plastic", base_demand * 0.3)

    # 3. ADJUDICATION
    plan.calculate_suv()

    # 4. METABOLISM & INNOVATION
    earth.tick()
    plan.innovate()

print("\n" + "!"*40)
print("   STABLE CIVILIZATION ACHIEVED")
print("!"*40)
